spring:
  application:
    name: eureka-server-7001
server:
  port: 7001
  
security:
  basic:
    enabled: false   # 启用安全认证处理
#  user:
#    name: edmin     # 用户名
#    password: mldnjava  # 密码


#在默认情况下erureka server也是一个eureka client ,
#           通过register-with-eureka=false,fetch-registry=false表明当前服务是一个eureka server 
eureka: 
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka-7002.com:7002/eureka,http://eureka-7003.com:7003/eureka
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false     # 不通过eureka获取注册信息,
  instance: # eureak实例定义
    hostname: eureka-7001.com # 定义Eureka实例所在的主机名称